apiVersion: v1
kind: Service
metadata:
  name: cdn-ingress-controller
  namespace: jiome
spec:
  type: LoadBalancer
  selector:
    app: cdn-ingress-controller
  ports:
    - name: http
      port: 80
      targetPort: 80

