apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: jiome
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/manwolframio/cdn-backend:latest 
        ports:
        - containerPort: 5200

