# Empleado 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: jiome
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/manwolframio/cdn-backend:v2.1
        ports:
        - containerPort: 5200

